name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - pyproject.toml
      - requirements*.txt
      - README.md

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install . pdoc

      - name: Gera documentação
        run: |
          pdoc html interpoladores utils io --output-dir docs --force

      - name: Publica no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages

